SRCDIR = ..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = cat cmp cp echo halt hex-dump ls mcat mcp mkdir pwd rm shell \
	bubsort insult lineup matmult recursor login auth useradd passwd userdel authtest id sudo \
	whoami usermod who addtest chmodtest chmod touch touchtest su addgroup

# Should work from project 2 onward.
cat_SRC = cat.c
cmp_SRC = cmp.c
cp_SRC = cp.c
echo_SRC = echo.c
halt_SRC = halt.c
hex-dump_SRC = hex-dump.c
insult_SRC = insult.c
lineup_SRC = lineup.c
ls_SRC = ls.c
recursor_SRC = recursor.c
rm_SRC = rm.c
login_SRC = login.c
auth_SRC = auth.c
useradd_SRC = useradd.c
passwd_SRC = passwd.c
userdel_SRC = userdel.c
authtest_SRC = authtest.c
id_SRC = id.c
sudo_SRC = sudo.c
whoami_SRC = whoami.c
usermod_SRC = usermod.c
who_SRC = who.c
addtest_SRC = addtest.c
chmodtest_SRC = chmodtest.c
chmod_SRC = chmod.c
touch_SRC = touch.c
touchtest_SRC = touchtest.c
su_SRC = su.c

# Should work in project 3; also in project 4 if VM is included.
bubsort_SRC = bubsort.c
matmult_SRC = matmult.c
mcat_SRC = mcat.c
mcp_SRC = mcp.c

# Should work in project 4.
mkdir_SRC = mkdir.c
pwd_SRC = pwd.c
shell_SRC = shell.c

addgroup_SRC = addgroup.c

include $(SRCDIR)/Make.config
include $(SRCDIR)/Makefile.userprog
